{
  "language": "java",
  "os": [
    "windows"
  ],
  "dist": "xenial",
  "jdk": [
    "openjdk8"
  ],
  "branches": {
    "only": [
      "master"
    ]
  },
  "cache": {
    "directories": [
      "$HOME/.m2/repository",
      "$HOME/.gradle"
    ]
  },
  "script": [
    "./gradlew clean build"
  ],
  "notifications": {
    "slack": [
      {
        "rooms": [
          travis encrypt "hyuerica-selab:rQA2uoVX2rHX9SLGfqPoeJMw" --add notifications.slack -r SWdevelop-569/Invaders
        ]
      }
    ]
  }
}
